create table
  public.customer (
    user_id bigint generated by default as identity,
    customer_name text null,
    payment text null,
    constraint new_customer_pkey primary key (user_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer not null default 0,
    num_red_ml integer not null default 0,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint new_global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.orders (
    order_no bigint generated by default as identity,
    user_id bigint null,
    potion_type text null,
    quantity integer null default 0,
    constraint order_pkey primary key (order_no),
    constraint orders_potion_type_fkey foreign key (potion_type) references potions (potion_type),
    constraint orders_user_id_fkey foreign key (user_id) references customer (user_id)
  ) tablespace pg_default;

create table
  public.potions (
    recipe integer[] null,
    price integer null default 0,
    inventory integer null default 0,
    potion_type text not null,
    desired_inventory integer not null default 0,
    name text null,
    constraint potions_pkey primary key (potion_type)
  ) tablespace pg_default;
